// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjokHnGvVStYroISGOQPgiw4oOBmTCAeY',
    appId: '1:454482395196:web:ba9b67fb9b6164c96b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    authDomain: 'ecommerce-ffdbe.firebaseapp.com',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
    measurementId: 'G-8Q5JJJQT9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMc3z9EKPLeA62ut5KSiD5rrkmkaLSqLg',
    appId: '1:454482395196:android:41b4bc445e6144556b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiJTCSX281Wx5UWx4yQZegcaiNT0DwkTM',
    appId: '1:454482395196:ios:2727f018e5de770a6b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
    androidClientId: '454482395196-0tgf5ecvp1alhu5pjcv3m4d6lkqd1hgg.apps.googleusercontent.com',
    iosClientId: '454482395196-9n7gq27td5esiu5rb5iimj2m0peq7jqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiJTCSX281Wx5UWx4yQZegcaiNT0DwkTM',
    appId: '1:454482395196:ios:c3708f19a8b7afdb6b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
    androidClientId: '454482395196-0tgf5ecvp1alhu5pjcv3m4d6lkqd1hgg.apps.googleusercontent.com',
    iosClientId: '454482395196-vvtf08750lnmsbc0vfhmks940dm14bv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomer.RunnerTests',
  );
}
